all: upgrade to latest x/tools version
Upgrading to newest x/tools was performed with these steps:

```
% go get golang.org/x/tools@v0.1.11-0.20220504225841-45c8a7131235
% go get golang.org/x/tools/internal/gocommand@v0.1.11-0.20220504225841-45c8a7131235
% go mod download github.com/yuin/goldmark
```

With this update `interface{}` is now rendered with the new builtin type
`any`, which interfers with the golden test data in the debug/render
package. The golden files have been simply updated with the following
command:

```
% sed -i 's/interface{}/any/g' internal/pkg/debug/render/testdata/*
```

The following test fails after this upgrade:

```
% go1.18.1 test github.com/google/go-flow-levee/internal/pkg/earpointer
--- FAIL: TestMethodInvoke (0.00s)
    analysis_test.go:1212:
          got: {**T2:f.arg0}: [T1->g.t0], {*T1:f.arg0,*T2:f.t0,g.t0}: [], {*T1:f.x,*T2:f.x,g.x}: [], {*T2:f.arg0}: --> **T2:f.arg0, {*g.x2}: [T1->g.t0], {g.x2}: --> *g.x2
         want: {**T2:f.arg0}: [T1->*T1:f.arg0], {*T1:f.arg0,*T2:f.t0,g.t0}: [], {*T1:f.x,*T2:f.x,g.x}: [], {*T2:f.arg0}: --> **T2:f.arg0, {*g.x2}: [T1->*T1:f.arg0], {g.x2}: --> *g.x2
FAIL
FAIL	github.com/google/go-flow-levee/internal/pkg/earpointer	0.054s
FAIL
```

The following test panics with go1.18.1 and with this upgrade it fails:

```
% go1.18.1 test github.com/google/go-flow-levee/internal/pkg/levee
--- FAIL: TestLeveeEAR (5.97s)
    analysistest.go:455: levee_analysistest/example/tests/position/tests.go:36:11: diagnostic "a source has reached a sink\n source: /home/chressie/src/github.com/google/go-flow-levee/internal/pkg/levee/testdata/src/levee_analysistest/example/tests/position/tests.go:35:7" does not match pattern "a source has reached a sink\n source: .*tests.go:34:2"
    analysistest.go:455: levee_analysistest/example/tests/position/tests.go:42:11: diagnostic "a source has reached a sink\n source: /home/chressie/src/github.com/google/go-flow-levee/internal/pkg/levee/testdata/src/levee_analysistest/example/tests/position/tests.go:42:12" does not match pattern "a source has reached a sink\n source: .*tests.go:42:24"
    analysistest.go:519: levee_analysistest/example/tests/position/tests.go:36: no diagnostic was reported matching "a source has reached a sink\n source: .*tests.go:34:2"
    analysistest.go:519: levee_analysistest/example/tests/position/tests.go:42: no diagnostic was reported matching "a source has reached a sink\n source: .*tests.go:42:24"
--- FAIL: TestLevee (0.54s)
    analysistest.go:455: levee_analysistest/example/tests/position/tests.go:36:11: diagnostic "a source has reached a sink\n source: /home/chressie/src/github.com/google/go-flow-levee/internal/pkg/levee/testdata/src/levee_analysistest/example/tests/position/tests.go:35:7" does not match pattern "a source has reached a sink\n source: .*tests.go:34:2"
    analysistest.go:455: levee_analysistest/example/tests/position/tests.go:42:11: diagnostic "a source has reached a sink\n source: /home/chressie/src/github.com/google/go-flow-levee/internal/pkg/levee/testdata/src/levee_analysistest/example/tests/position/tests.go:42:12" does not match pattern "a source has reached a sink\n source: .*tests.go:42:24"
    analysistest.go:519: levee_analysistest/example/tests/position/tests.go:36: no diagnostic was reported matching "a source has reached a sink\n source: .*tests.go:34:2"
    analysistest.go:519: levee_analysistest/example/tests/position/tests.go:42: no diagnostic was reported matching "a source has reached a sink\n source: .*tests.go:42:24"
    analysistest.go:519: levee_analysistest/example/tests/stdlib/interface_funcs.go:45: no diagnostic was reported matching `a source has reached a sink`
FAIL
FAIL	github.com/google/go-flow-levee/internal/pkg/levee	6.870s
FAIL
```